name: Main

on: [ push, pull_request ]

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
      PGHOST: localhost
      PGUSER: postgres

    services:
      postgres:
        image: postgres:11.4
        ports: [ "5432:5432" ]
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v1
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Install PostgreSQL libs
        run: sudo apt-get -yqq install libpq-dev

      - name: Setup Database
        run: bin/rails db:create db:schema:load

      - name: Build and test with rspec
        run: ./bin/rspec